import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { collection, addDoc, getDocs, query, orderBy, limit } from 'firebase/firestore';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { db, auth } from '../../firebase/config';
import Icon from '../../components/Icons';
import './StaffCreate.css';

interface Department {
  id: string;
  name: string;
  description: string;
}

interface Role {
  id: string;
  name: string;
  description: string;
}

const StaffCreate = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    department: '',
    role: '',
    employeeId: '',
    joinDate: '',
    address: ''
  });
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [createUserAccount, setCreateUserAccount] = useState(true);
  const [fullyResponsible, setFullyResponsible] = useState(false);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [lastEmployeeId, setLastEmployeeId] = useState<string>('');
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');
  const navigate = useNavigate();

  useEffect(() => {
    const initialize = async () => {
      await fetchDepartments();
      await fetchRoles();
      await fetchLastEmployeeId();
    };
    initialize();
  }, []);

  useEffect(() => {
    // Auto-generate Employee ID when lastEmployeeId is fetched or changes
    // Only generate if formData.employeeId is empty (to avoid overwriting user input)
    if (lastEmployeeId !== '' && lastEmployeeId !== 'Loading...' && !formData.employeeId) {
      generateNextEmployeeId();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lastEmployeeId]);

  const fetchLastEmployeeId = async () => {
    try {
      // Fetch from both staffs and employees collections
      const staffsRef = collection(db, 'staffs');
      const employeesRef = collection(db, 'employees');
      
      const staffsQuery = query(staffsRef, orderBy('employeeId', 'desc'), limit(50));
      const employeesQuery = query(employeesRef, orderBy('employeeId', 'desc'), limit(50));
      
      const [staffsSnapshot, employeesSnapshot] = await Promise.all([
        getDocs(staffsQuery),
        getDocs(employeesQuery)
      ]);
      
      let maxEmpNumber = 0;
      let maxFmcNumber = 0;
      
      // Get last IDs from staffs collection
      staffsSnapshot.docs.forEach(doc => {
        const employeeId = doc.data().employeeId;
        if (employeeId && typeof employeeId === 'string') {
          if (employeeId.startsWith('EMP')) {
            const number = parseInt(employeeId.replace('EMP', ''), 10);
            if (!isNaN(number) && number > maxEmpNumber) {
              maxEmpNumber = number;
            }
          } else if (employeeId.startsWith('FMC')) {
            const number = parseInt(employeeId.replace('FMC', ''), 10);
            if (!isNaN(number) && number > maxFmcNumber) {
              maxFmcNumber = number;
            }
          }
        }
      });
      
      // Get last IDs from employees collection
      employeesSnapshot.docs.forEach(doc => {
        const employeeId = doc.data().employeeId;
        if (employeeId && typeof employeeId === 'string') {
          if (employeeId.startsWith('EMP')) {
            const number = parseInt(employeeId.replace('EMP', ''), 10);
            if (!isNaN(number) && number > maxEmpNumber) {
              maxEmpNumber = number;
            }
          } else if (employeeId.startsWith('FMC')) {
            const number = parseInt(employeeId.replace('FMC', ''), 10);
            if (!isNaN(number) && number > maxFmcNumber) {
              maxFmcNumber = number;
            }
          }
        }
      });
      
      // Use the highest number from either prefix
      const maxNumber = Math.max(maxEmpNumber, maxFmcNumber);
      const lastId = maxNumber > 0 ? `FMC${maxNumber.toString().padStart(3, '0')}` : 'None';
      setLastEmployeeId(lastId);
    } catch (error) {
      console.error('Error fetching last employee ID:', error);
      setLastEmployeeId('Error loading');
    }
  };

  const generateNextEmployeeId = () => {
    try {
      let nextNumber = 1;
      
      if (lastEmployeeId && lastEmployeeId !== 'None' && lastEmployeeId !== 'Error loading' && lastEmployeeId !== '') {
        // Check for both EMP and FMC prefixes
        if (lastEmployeeId.startsWith('EMP')) {
          const lastNumber = parseInt(lastEmployeeId.replace('EMP', ''), 10);
          if (!isNaN(lastNumber) && lastNumber > 0) {
            nextNumber = lastNumber + 1;
          }
        } else if (lastEmployeeId.startsWith('FMC')) {
          const lastNumber = parseInt(lastEmployeeId.replace('FMC', ''), 10);
          if (!isNaN(lastNumber) && lastNumber > 0) {
            nextNumber = lastNumber + 1;
          }
        }
      }
      
      // Always generate FMC IDs now
      const newEmployeeId = `FMC${nextNumber.toString().padStart(3, '0')}`;
      setAutoGeneratedId(newEmployeeId);
      
      // Auto-fill the Employee ID field if it's empty
      if (!formData.employeeId) {
        setFormData(prev => ({ ...prev, employeeId: newEmployeeId }));
      }
    } catch (error) {
      console.error('Error generating employee ID:', error);
    }
  };

  const fetchDepartments = async () => {
    try {
      const snapshot = await getDocs(collection(db, 'departments'));
      if (!snapshot.empty) {
        const departmentsData = snapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data()
        })) as Department[];
        setDepartments(departmentsData);
      }
    } catch (error) {
      console.error('Error fetching departments:', error);
    }
  };

  const fetchRoles = async () => {
    try {
      const snapshot = await getDocs(collection(db, 'roles'));
      if (!snapshot.empty) {
        const rolesData = snapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data()
        })) as Role[];
        setRoles(rolesData);
      }
    } catch (error) {
      console.error('Error fetching roles:', error);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    // Validate password if creating user account
    if (createUserAccount) {
      if (!password) {
        setMessage('Password is required when creating user account.');
        setLoading(false);
        return;
      }
      if (password.length < 6) {
        setMessage('Password must be at least 6 characters long.');
        setLoading(false);
        return;
      }
      if (password !== confirmPassword) {
        setMessage('Passwords do not match.');
        setLoading(false);
        return;
      }
    }

    try {
      let authUserId = null;

      // Create Firebase Auth user if enabled
      if (createUserAccount && password) {
        try {
          const userCredential = await createUserWithEmailAndPassword(
            auth,
            formData.email,
            password
          );
          authUserId = userCredential.user.uid;
        } catch (authError: any) {
          console.error('Error creating user account:', authError);
          setMessage(`Error creating user account: ${authError.message}`);
          setLoading(false);
          return;
        }
      }

      // Create staff document in Firestore
      await addDoc(collection(db, 'staffs'), {
        ...formData,
        authUserId: authUserId,
        hasUserAccount: createUserAccount && !!authUserId,
        fullyResponsible: fullyResponsible,
        createdAt: new Date(),
        status: 'active'
      });

      setMessage('Staff created successfully!');
      setFormData({
        name: '',
        email: '',
        phone: '',
        department: '',
        role: '',
        employeeId: '',
        joinDate: '',
        address: ''
      });
      setPassword('');
      setConfirmPassword('');
      setFullyResponsible(false);
    } catch (error) {
      console.error('Error creating staff:', error);
      setMessage('Error creating staff. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="full-page">
      <div className="staff-create">
        <div className="page-header-with-back">
          <button className="back-button" onClick={() => navigate('/staffs')}>
            <Icon name="chevron-left" /> Back
          </button>
          <h2>Create New Staff</h2>
        </div>
      <form onSubmit={handleSubmit} className="staff-form">
        <div className="form-row">
          <div className="form-group">
            <label>Full Name *</label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
            />
          </div>
          <div className="form-group">
            <label>Employee ID *</label>
            <div className="employee-id-container">
              <input
                type="text"
                name="employeeId"
                value={formData.employeeId}
                onChange={handleChange}
                required
                placeholder="Auto-generated"
              />
              <button
                type="button"
                className="btn-auto-generate"
                onClick={() => {
                  setFormData(prev => ({ ...prev, employeeId: autoGeneratedId }));
                }}
                title="Use auto-generated ID"
              >
                Auto Generate
              </button>
            </div>
            <div className="employee-id-info">
              <span className="info-label">Last Used:</span>
              <span className="info-value">{lastEmployeeId || 'Loading...'}</span>
              {autoGeneratedId && (
                <>
                  <span className="info-separator">|</span>
                  <span className="info-label">Next ID:</span>
                  <span className="info-value next-id">{autoGeneratedId}</span>
                </>
              )}
            </div>
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Email *</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              required
            />
          </div>
          <div className="form-group">
            <label>Phone *</label>
            <input
              type="tel"
              name="phone"
              value={formData.phone}
              onChange={handleChange}
              required
            />
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Department *</label>
            <select
              name="department"
              value={formData.department}
              onChange={handleChange}
              required
              disabled={departments.length === 0}
            >
              <option value="">{departments.length === 0 ? 'Loading departments...' : 'Select Department'}</option>
              {departments.map(dept => (
                <option key={dept.id} value={dept.name}>{dept.name}</option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Role *</label>
            <select
              name="role"
              value={formData.role}
              onChange={handleChange}
              required
              disabled={roles.length === 0}
            >
              <option value="">{roles.length === 0 ? 'Loading roles...' : 'Select Role'}</option>
              {roles.map(role => (
                <option key={role.id} value={role.name}>{role.name}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Join Date *</label>
            <input
              type="date"
              name="joinDate"
              value={formData.joinDate}
              onChange={handleChange}
              required
            />
          </div>
        </div>

        <div className="form-group">
          <label>Address</label>
          <textarea
            name="address"
            value={formData.address}
            onChange={handleChange}
            rows={3}
          />
        </div>

        <div className="form-group" style={{ marginTop: '20px', paddingTop: '20px', borderTop: '1px solid #e5e7eb' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={fullyResponsible}
              onChange={(e) => setFullyResponsible(e.target.checked)}
              style={{ width: '18px', height: '18px', cursor: 'pointer' }}
            />
            <span style={{ fontWeight: 600, color: '#374151' }}>Fully Responsible</span>
          </label>
          <p style={{ marginTop: '8px', marginLeft: '28px', color: '#6b7280', fontSize: '0.9rem' }}>
            Mark this staff member as fully responsible with complete authority
          </p>
        </div>

        <div className="form-group" style={{ marginTop: '20px', paddingTop: '20px', borderTop: '1px solid #e5e7eb' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={createUserAccount}
              onChange={(e) => setCreateUserAccount(e.target.checked)}
              style={{ width: '18px', height: '18px', cursor: 'pointer' }}
            />
            <span style={{ fontWeight: 600, color: '#374151' }}>Create User Account for Page Access</span>
          </label>
          <p style={{ marginTop: '8px', marginLeft: '28px', color: '#6b7280', fontSize: '0.9rem' }}>
            Enable this to create login credentials for the staff member
          </p>
        </div>

        {createUserAccount && (
          <>
            <div className="form-row">
              <div className="form-group">
                <label>Password *</label>
                <input
                  type="password"
                  name="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Enter password (min. 6 characters)"
                  required={createUserAccount}
                  disabled={loading}
                />
              </div>
              <div className="form-group">
                <label>Confirm Password *</label>
                <input
                  type="password"
                  name="confirmPassword"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="Confirm password"
                  required={createUserAccount}
                  disabled={loading}
                />
              </div>
            </div>
          </>
        )}

        {message && (
          <div className={`message ${message.includes('Error') ? 'error' : 'success'}`}>
            {message}
          </div>
        )}

        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading ? 'Creating...' : 'Create Staff'}
        </button>
      </form>
      </div>
    </div>
  );
};

export default StaffCreate;








